spring:
  rabbitmq:
    host: 114.132.47.155
    port: 5672
    username: admin
    password: admin
#    template:
#      mandatory: true
    publisher-confirm-type: correlated
    publisher-returns: true

  main:
    allow-circular-references: true